# Site settings

url: transgresspress.github.io
name: Transgress Press
name_managing_editor: Trystan Cotten
name_assistant_editor: Mitch Kellaway
name_acquisitions_editor: Maya Scott-Chung

email: info@transgresspress.org
email_purchasing: purchasing@transgresspress.org
email_managing_editor: trystan@transgresspress.org
email_assistant_editor: mitch@transgresspress.org
email_acquisitions_editor: acquisitions@transgresspress.org

message_credit: Site by Harlan Kellaway &bull; Theme by <a href="http://mbeagency.com/" target="_blank">MBE</a>

facebook_url: http://www.facebook.com/transgress.press
twitter_url: http://twitter.com/trans_books

# Build settings
markdown: kramdown
permalink: pretty
