# Site settings
name: Transgress Press
name_managing_editor: Trystan
name_acquisitions_editor: Maya

email: info@transgresspress.org
email_purchasing: purchasing@transgresspress.org
email_photos: photos@transgresspress.org
email_managing_editor: trystan@transgresspress.org
email_acquisitions_editor: acquisitions@transgresspress.org

message_copyright: Copyright &copy; 2014 Transgress Press
message_credit: Site by Harlan Kellaway &bull; Design by <a href="http://mbeagency.com/" target="_blank">MBE</a>

facebook_url: http://www.facebook.com/transgress.press
twitter_url: http://twitter.com/trans_books

# Build settings
markdown: kramdown
permalink: pretty
