# Site settings

facebook_url: http://www.facebook.com/transgress.press
twitter_url: http://twitter.com/trans_books

message_404: "Head back to Transgress Press"

# Build settings
markdown: kramdown
permalink: pretty
