# Site settings

message_copyright: Copyright &copy; 2014 Transgress Press
message_credit: Site by Harlan Kellaway &bull; Design by <a href="http://mbeagency.com/" target="_blank">MBE</a>

facebook_url: http://www.facebook.com/transgress.press
twitter_url: http://twitter.com/trans_books

message_404: "Head back to Transgress Press"

# Build settings
markdown: kramdown
permalink: pretty
