# Site settings

url: transgresspress.org
name: Transgress Press

name_managing_editor: Trystan Cotten
name_assistant_editor: N/A
name_acquisitions_editor: Maya Scott-Chung

email: info@transgresspress.org
email_purchasing: purchasing@transgresspress.org
email_managing_editor: trystan@transgresspress.org
email_assistant_editor: #
email_acquisitions_editor: acquisitions@transgresspress.org

message_credit:

facebook_url: http://www.facebook.com/transgress.press
twitter_url: http://twitter.com/trans_books

# Build settings
markdown: kramdown
permalink: pretty
